format_version = 1

[project]
name = "project"
ioc_file = "project.ioc"

[dependencies]
packages = [
    "Core::IController",
    "MotorDrivers::Controller",
    "MotorDrivers::Core",
    "MotorDrivers::DJI",
    "Trajectory::HomingMotorTrajectory",
    "Trajectory::MotorTrajectory",
    "VelocityProfile::Core",
    "VelocityProfile::SCurve",
    "bsp::GPIO_Driver",
    "libs::Concurrency",
    "utils",
]
