include_guard(GLOBAL)

# Generated by cpkg sync.
# Include this file from the root CMakeLists.txt of your STM32CubeMX project.
# Use wtr_link_packages(<target>) for plain target_link_libraries(...).
# Use wtr_link_packages_public(<target>) to link with PUBLIC scope.

set(WTR_MANAGED_REPOSITORIES
    BasicComponents
    Core
    MotorDrivers
    TrajectoryControl
    VelocityProfile
)

set(WTR_MANAGED_PACKAGE_DIRS
    Modules/BasicComponents/libs/concurrency
    Modules/Core/IController
    Modules/MotorDrivers/core
    Modules/BasicComponents/libs/control/pid_motor
    Modules/MotorDrivers/controllers
    Modules/BasicComponents/libs/utils/ring_buffer
    Modules/BasicComponents/utils
    Modules/BasicComponents/bsp/can_driver
    Modules/BasicComponents/services/watchdog
    Modules/MotorDrivers/motors/DJI
    Modules/VelocityProfile/Core
    Modules/VelocityProfile/SCurve
    Modules/BasicComponents/libs/control/pid_pd
    Modules/TrajectoryControl/MotorTrajectory
    Modules/TrajectoryControl/HomingMotorTrajectory
)

foreach(_wtr_package_dir IN LISTS WTR_MANAGED_PACKAGE_DIRS)
    if(NOT EXISTS "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}/CMakeLists.txt")
        message(FATAL_ERROR "Missing managed package '${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}'. Run cpkg sync.")
    endif()

    add_subdirectory(
        "${CMAKE_CURRENT_LIST_DIR}/../${_wtr_package_dir}"
        "${CMAKE_BINARY_DIR}/cpkg/${_wtr_package_dir}"
    )
endforeach()

set(WTR_DIRECT_PACKAGE_TARGETS
    Core::IController
    MotorDrivers::Controller
    MotorDrivers::Core
    MotorDrivers::DJI
    Trajectory::HomingMotorTrajectory
    Trajectory::MotorTrajectory
    VelocityProfile::Core
    VelocityProfile::SCurve
    libs::Concurrency
    utils
)

set(WTR_RESOLVED_PACKAGE_TARGETS
    libs::Concurrency
    Core::IController
    MotorDrivers::Core
    libs::PIDMotor
    MotorDrivers::Controller
    libs::RingBuffer
    utils
    bsp::CANDriver
    services::Watchdog
    MotorDrivers::DJI
    VelocityProfile::Core
    VelocityProfile::SCurve
    libs::PID_PD
    Trajectory::MotorTrajectory
    Trajectory::HomingMotorTrajectory
    stm32cubemx
)

add_library(wtr_project_dependencies INTERFACE)
target_link_libraries(wtr_project_dependencies INTERFACE ${WTR_DIRECT_PACKAGE_TARGETS})

function(wtr_link_packages target)
    target_link_libraries(${target} ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()

function(wtr_link_packages_public target)
    target_link_libraries(${target} PUBLIC ${WTR_DIRECT_PACKAGE_TARGETS})
endfunction()
